services:
  web:
    build: .
    container_name: todo-web
    volumes:
      - ./:/app
    working_dir: /app
    command: ["apache2-foreground"]
    ports:
      - "8080:80"
    restart: unless-stopped
